name: Publish Package
on:
  push:
    tags:
      - 'v**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to NPM
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'
          run: |
              npm ci
              npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
